sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t alexdaciuk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexdaciuk/react-test npm test

after_success:
  - docker build -t alexdaciuk/multi-client ./client
  - docker build -t alexdaciuk/multi-nginx ./nginx
  - docker build -t alexdaciuk/multi-server ./server
  - docker build -t alexdaciuk/multi-worker ./worker
  - echo "$dockerPassword" | docker login -u "$dockerUser" --password-stdin
  - docker push alexdaciuk/multi-client
  - docker push alexdaciuk/multi-nginx
  - docker push alexdaciuk/multi-server
  - docker push alexdaciuk/multi-worker
